#include <cs50.h>
#include <stdio.h>

int get_cents(void);
int calculate_quarters(int cents);
int calculate_dimes(int cents);
int calculate_nickels(int cents);
int calculate_pennies(int cents);

int main(void)
{
    // Ask how many cents the customer is owed
    int cents = get_cents();

    // Calculate the number of quarters to give the customer
    int quarters = calculate_quarters(cents);
    cents = cents - quarters * 25;

    // Calculate the number of dimes to give the customer
    int dimes = calculate_dimes(cents);
    cents = cents - dimes * 10;

    // Calculate the number of nickels to give the customer
    int nickels = calculate_nickels(cents);
    cents = cents - nickels * 5;

    // Calculate the number of pennies to give the customer
    int pennies = calculate_pennies(cents);
    cents = cents - pennies * 1;

    // Sum coins
    int coins = quarters + dimes + nickels + pennies;

    // Print total number of coins to give the customer
    printf("%i\n", coins);

}

int get_cents(void)
{
    // TODO
    int cents;
    do
    {
        cents = get_int("Enter number of cents: ");
    }
    while(cents < 0);
    return cents;

}

int calculate_quarters(int cents)
{
    // TODO
    int amountQuarters = 1;
    int remainder = 1;
    //if cents % 25 is 0, that means it can immediately return the amount of pennies we need by dividing amount of cents with 25
    if(cents % 25 == 0)
    {
        return amountQuarters = cents / 25;
    }
    //otherwise calculate the remainder and subtract remainder from amount of cents to get a number which you can divide with 25.
    else
    {
        remainder = cents % 25;
        return amountQuarters = (cents-remainder) / 25;
    }

    //same goes for all other functions
}

int calculate_dimes(int cents)
{
    // TODO
    int amountDimes = 1;
    int remainder = 1;
    if(cents % 10 == 0)
    {
        return amountDimes = cents / 10;
    }
    else
    {
        remainder = cents % 10;
        return amountDimes = (cents-remainder) / 10;
    }

}

int calculate_nickels(int cents)
{

    int amountNickels = 1;
    int remainder = 1;
    if(cents % 5 == 0)
    {
        return amountNickels = cents / 5;
    }
    else
    {
        remainder = cents % 5;
        return amountNickels = (cents-remainder) / 5;
    }
}

int calculate_pennies(int cents)
{
    // TODO
    int amountPennies = 1;
    int remainder = 1;
    if(cents % 1 == 0)
    {
        return amountPennies = cents / 1;
    }
    else
    {
        remainder = cents % 1;
        return amountPennies = (cents-remainder) / 1;
    }
}

/*Results for cs50/problems/2022/x/cash generated by check50 v3.3.7
:) cash.c exists
:) cash.c compiles
:) get_cents returns integer number of cents
:) get_cents rejects negative input
:) get_cents rejects a non-numeric input of "foo"
:) calculate_quarters returns 2 when input is 50
:) calculate_quarters returns 1 when input is 42
:) calculate_dimes returns 1 when input is 10
:) calculate_dimes returns 1 when input is 15
:( calculate_dimes returns 7 when input is 73
    expected "7", not "0"
:) calculate_nickels returns 1 when input is 5
:( calculate_nickels returns 5 when input is 28
    expected "5", not "0"
:( calculate_pennies returns 4 when input is 4
    expected "4", not "1"
:) input of 41 cents yields output of 4 coins
:( input of 160 cents yields output of 7 coins
    expected "7\n", not "4\n" */
